# ----------------------- #
#      Main Configs       #
# ----------------------- #
# Google services
google_analytics: UA-90765310-1
url: https://nesio.github.io/website/
title: Nesio
email: nesilio@gmail.com
author: Guillaume Ottavianoni
description: Nesio une ESN,SS2I qui propose des solutions Métiers, Informatique, Data, Business de prestation,  de formation ou de freelance dans les alentours de Toulouse & Castelnaudary.
keywords: nesio, ss2i, esn, prestation, informatique, castelnaudary, toulouse, web, digital, conseil, consulting,formation, freelance, prestation, supply chain,marketing, digital, data, business, agilité, agilite, start-up 
copyright: 'Copyright &copy; 2016 Nesio All Rights Reserved.'
credits: 'Powered by <a href="https://jekyllrb.com/">Jekyll</a><br>
Hosted by <a href="https://pages.github.com/">Github</a><br>
Inspired by <a href="http://startbootstrap.com/">Start Bootstrap</a>
'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/NesioFr
  - title: github
    url: https://github.com/nesio
  - title: linkedin
    url: https://www.linkedin.com/in/nesioFr/