# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://nesio.github.io/website/
title: Nesio
email: nesilio@gmail.com
author: Guillaume Ottavianoni
description: > 'Implanté a Castelnaudary, Nesio est une strat-up qui propose des solutions Métiers et IT comme en prestation dans le bassin Toulousain et alentours
copyright: 'Copyright &copy; 2016 Nesio All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/gottavianoni
  - title: github
    url: https://github.com/gottavianoni
  - title: linkedin
    url: https://linkedin.com/in/gottavianoni