# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://nesio.github.io/website/
title: Nesio
email: nesilio@gmail.com
author: Guillaume Ottavianoni
description: #< 'Nesio une start-up qui propose des solutions Métiers et IT comme en prestation dans les alentours de Toulouse & Castelnaudary
copyright: 'Copyright &copy; 2016 Nesio All Rights Reserved.'
credits: 'Credits : Le design de ce site est inspiré du thème en libre distribution Landing Page créer par <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/gottavianoni
  - title: github
    url: https://github.com/gottavianoni
  - title: linkedin
    url: https://linkedin.com/in/gottavianoni